theme: jekyll-theme-slate
title: Welcome to Michael's Homepage
description: A website to stay update on the many cool projects I'm currently working on.
show_downloads: false
github:
  zip_url: 
  another_url:
